on: [push]

name: Rust CI with Cargo

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build_and_test:
    name: EZInput for Bevy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: build